FROM node:slim

# Install dependencies
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
ADD . /work
WORKDIR /work
RUN yarn
RUN yarn prestart:prod

# Run the users microservice when the container starts.
ENTRYPOINT yarn start:prod

# Service listens on port 3000.
# EXPOSE 3000
